/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bjbbwgircgsilxsgpdre"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqYmJ3Z2lyY2dzaWx4c2dwZHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzOTg0NzcsImV4cCI6MjA4NTk3NDQ3N30.55isppvM-NjvwNcoAingFF-EKYoogP8f8O-Pcq5x09o"